config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :home, only: [:show]
  devise_for :users
  resources :messages, only: [:index, :create]
  namespace :owner do
    resources :buffets, only: [:new, :create, :show, :edit, :update] do
      resources :events, only: [:new, :create, :show, :edit, :update]
    end
    resources :event_prices, only: [:new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :dashboards, only: [:index]
  end

  namespace :client do
    resources :buffets do
      get 'search', on: :collection
    end
    resources :orders, only: [:new, :create, :show, :update]
    resources :dashboards, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show] do
        get 'search/:query', on: :collection, to: "buffets#search"
        get 'events', on: :member, to: "buffets#events"
        get ':event_id/:event_date/:total_guests', to: "buffets#check_availability"
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buffet
  belongs_to :event
  belongs_to :user
  belongs_to :payment_method, optional: true
  enum status: { pending: 0, confirmed: 1, approved: 2, rejected: 3 }
  enum adjustment_type: { nonexistent: 0, discount: 1, surcharge: 2 }
  before_validation :generate_code, on: :create
  before_validation :set_address_if_blank
  before_validation :set_price
  validates :status, inclusion: { in: statuses.keys }
  validates :adjustment_type, inclusion: { in: adjustment_types.keys }
  validates :event_date, presence: true
  validates :total_guests, presence: true
  validates :code, presence: true
  validates :address, presence: true
  validates :price, presence: true
  validates :payment_method, presence: true, if: :approved?
  validates :confirmation_date, presence: true, if: :approved?
  validate :confirmation_date_cannot_be_in_the_past, if: :approved?
  validate :event_date_cannot_be_in_the_past
  validate :total_guests_must_be_within_event_limits

  def set_price
    if self.event_date.on_weekday?
      self.price = calculate(self.event.event_prices.find_by(day_type: :weekday))
    else
      self.price = calculate(event.event_prices.find_by(day_type: :weekend))
    end
  end

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def set_address_if_blank
    self.address = self.buffet.address.full_address if self.address.blank?
  end

  def event_date_cannot_be_in_the_past
    if event_date < Date.today
      errors.add(:event_date, I18n.t("error.models.order.cannot_be_in_the_past"))
    end
  end

  def confirmation_date_cannot_be_in_the_past
    if confirmation_date < Date.today
      errors.add(:confirmation_date,  I18n.t("error.models.order.cannot_be_in_the_past"))
    end
  end

  def total_guests_must_be_within_event_limits
    if self.total_guests <= 0 || self.total_guests > event.max_guests
      errors.add(:total_guests, I18n.t("error.models.order.total_guests_must_be_within_event_limits", max_guests: event.max_guests))
    end
  end

  def has_same_day_order?
    Order.where("event_id = ? AND event_date = ? AND buffet_id = ? AND (status != ? OR status != ?)",
                event_id, event_date, buffet_id, "rejected", "pending").any?
  end

  def self.adjustment_type_options
    adjustment_types.keys.map do |adjustment|
      [adjustment, I18n.t("activerecord.attributes.order.adjustment_types.#{adjustment}")]
    end
  end

  def self.approved?
    status == 'approved'
  end

  private

  def calculate(event_price)
    standard_price = event_price.standard_price # 9000
    unless total_guests < event.min_guests
      standard_price += (total_guests - event.min_guests) * event_price.extra_guest_price
    end
    apply_adjustments(standard_price)
  end

  def apply_adjustments(temporary_price)
    case self.adjustment_type
    when 'discount'
      return temporary_price - self.adjustment
    when 'surcharge'
      return temporary_price + self.adjustment
    end
    temporary_price
  end
end

app/controllers/client/orders_controller.rb
class  Client::OrdersController < ApplicationController
  before_action :authenticate_client
  before_action :check_order_owner, only: [:show, :update]
  def new
    @buffet = Buffet.find(params[:buffet_id])
    @event = @buffet.events.find(params[:event_id])
    @order = Order.new
  end

  def create
    @order = Order.new(params.require(:order).permit(:event_date, :total_guests, :address,
                                                     :additional_info, :buffet_id, :event_id))
    @order.user_id = current_user.id
    if @order.save
      return redirect_to client_order_path(@order), notice: t("notices.models.order.request.success")
    end
    @buffet = Buffet.find(params[:order][:buffet_id])
    @event = @buffet.events.find(params[:order][:event_id])
    flash.now[:notice] = t("notices.models.order.request.fail")
    render 'new'
  end

  def update
    @order = Order.find(params[:id])

    if @order.confirmation_date < Date.today
      @order.rejected!
      return redirect_to client_order_path(@order), notice: t("notices.models.order.expired_date")
    end

    if @order.update(params.require(:order).permit(:status))
      return redirect_to client_order_path(@order), notice: t("notices.models.order.confirmation.success")
    end
    flash.now[:notice] = t("notices.models.order.confirmation.success")
    render :new
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def check_order_owner
    @order = Order.find(params[:id])
    redirect_to root_path, notice: t("notices.access.access_denied") if current_user.id != @order.user_id
  end
end

app/controllers/owner/buffets_controller.rb
class Owner::BuffetsController < ApplicationController
  before_action :authenticate_owner, only: [:new, :create, :edit, :update, :show]
  before_action :set_buffet, only: [:edit, :show, :edit, :update]
  before_action :check_buffet_owner, only: [:edit, :update]

  def new
    @buffet = Buffet.new
    @buffet.build_address
  end

  def create
    @buffet = Buffet.new(buffet_params)
    @buffet.user = current_user
    if @buffet.save
      return redirect_to owner_buffet_path(@buffet), notice: t("notices.create.success", model_name: Buffet.model_name.human)
    end
    flash.now[:notice] = t("notices.create.fail", model_name: Buffet.model_name.human.downcase)
    render 'new'
  end

  def show; end

  def edit; end

  def update
    if @buffet.update(buffet_params)
      return redirect_to owner_buffet_path(@buffet), notice: t("notices.update.success", model_name: Buffet.model_name.human)
    end
    flash.now[:notice] = t("notices.update.fail", model_name: Buffet.model_name.human.downcase)
    render 'edit'
  end

  private

  def set_buffet
    @buffet = Buffet.find params[:id]
  end

  def buffet_params
    params.require(:buffet).permit(:brand_name, :company_name, :crn, :phone, :email,
                                   :description, address_attributes: [:id, :street_name,
                                    :house_or_lot_number, :neighborhood, :city, :state, :zip],
                                   payment_method_ids: [])
  end

  def check_buffet_owner
    set_buffet
    redirect_to root_path, notice: t("notices.access.access_denied") if current_user != @buffet.user
  end
end

app/controllers/owner/dashboards_controller.rb
class Owner::DashboardsController < ApplicationController
  before_action :authenticate_owner
  before_action :ensure_registered_buffet, only: [:index]
  def index
    @buffet = Buffet.find_by(user: current_user)
    @events = @buffet.events
  end
end

app/controllers/owner/event_prices_controller.rb
class Owner::EventPricesController < ApplicationController
  before_action :check_event, only: [:new, :edit, :create, :update]
  def new
    @event_price = EventPrice.new
  end

  def create
    @event_price = @event.event_prices.build(event_price_params)
    if @event.save
      redirect_to owner_buffet_event_path(@event.buffet, @event), notice: t("notices.models.event_price.register.success")
    else
      flash.now[:alert] =  t("notices.models.event_price.register.fail")
      render 'new'
    end
  end

  def edit
    @event_price = EventPrice.find params[:id]
  end

  def update
    @event_price = EventPrice.find params[:id]
    if @event_price.update(event_price_params)
      redirect_to owner_buffet_event_path(@event.buffet, @event), notice: t("notices.update.success", model_name: EventPrice.model_name.human)
    else
      flash.now[:alert] = t("notices.update.fail", model_name: EventPrice.model_name.human.downcase)
      render 'edit'
    end
  end

  private

  def event_price_params
    params.require(:event_price).permit(:standard_price, :extra_guest_price, :extra_hour_price, :day_type)
  end

  def check_event
    event = Event.find params[:event_id] || params[:event_price][:event_id]
    if event.buffet.user == current_user
      @event = event
    else
      redirect_to owner_dashboards_path, alert: t("notices.access.access_denied")
    end
  end
end

app/controllers/owner/events_controller.rb
class Owner::EventsController < ApplicationController
  def new
    @buffet = Buffet.find params[:buffet_id]
    @event = Event.new
  end

  def create
    @buffet = Buffet.find params[:buffet_id]
    @event = @buffet.events.build(event_params)
    if @event.save
      return redirect_to owner_buffet_event_path(@buffet, @event), notice: t("notices.create.success", model_name: Event.model_name.human)
    end
    flash.now[:notice] = t("notices.create.fail", model_name: Event.model_name.human.downcase)
    render 'new'
  end

  def show
    @buffet = Buffet.find params[:buffet_id]
    @event = Event.find params[:id]
  end

  def edit
    @buffet = Buffet.find params[:buffet_id]
    @event = Event.find params[:id]
  end

  def update
    @buffet = Buffet.find params[:buffet_id]
    @event = Event.find params[:id]
    if @event.update(event_params)
      return redirect_to owner_buffet_event_path(@buffet, @event), notice: t("notices.update.success", model_name: Event.model_name.human)
    end
    flash.now[:notice] = t("notices.update.success", model_name: Event.model_name.human.downcase)
    render 'edit'
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :min_guests, :max_guests, :standard_duration,
                                  :menu, :offsite_event, :offers_alcohol, :offers_decoration,
                                  :offers_valet_parking, photos: [])
  end
end

app/controllers/owner/orders_controller.rb
class Owner::OrdersController < ApplicationController
  before_action :authenticate_owner
  before_action :ensure_registered_buffet, only: [:index]

  def index
    buffet = Buffet.find_by(user: current_user)
    orders = Order.where(buffet_id: buffet.id)
    @pending_orders = orders.where(status: :pending)
    @confirmed_orders = orders.where(status: :confirmed)
    @approved_orders = orders.where(status: :approved)
    @rejected_orders = orders.where(status: :rejected)
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit
    @order = Order.find(params[:id])
    @buffet = Buffet.find_by(user: current_user)
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(params.require(:order).permit(:adjustment, :adjustment_type, :adjustment_description,
                                                   :payment_method_id, :confirmation_date, :status))
      redirect_to owner_order_path(@order), notice: t("notices.models.order.approve.success")
    else
      @buffet = Buffet.find_by(user: current_user)
      flash.now[:notice] = t("notices.models.order.approve.fail")
      render :edit
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_confirm_button(order)
    if order.status == 'approved' && order.confirmation_date > Date.today
      button_to 'Confirmar evento', client_order_path(order, order: { status: :confirmed }), method: :patch
    end
  end

  def render_reject_order_button(order)
    if order.status == 'pending' || order.status == 'approved'
      button_to 'Rejeitar evento', client_order_path(order, order: { status: :rejected} ), method: :patch
    end
  end

  def render_buffet_answer(order)
    if order.status == "approved" || @order.status == "confirmed"
      render partial: "shared/order_details", locals: {model: order}
    end
  end
end

app/views/owner/orders/edit.html.erb
<h1>Análise da solicitação <%= @order.code %></h1>

<div>
  <h2>Detalhes da solicitação</h2>
  <dl>
    <dt><%= Order.human_attribute_name :event_id %>:</dt>
    <dd><%= @order.event.name %></dd>

    <dt><%= Order.human_attribute_name :event_date %>:</dt>
    <dd><%= @order.event_date.strftime("%d/%m/%Y") %></dd>

    <dt><%= Order.human_attribute_name :total_guests %>:</dt>
    <dd><%= @order.total_guests %></dd>

    <dt><%= Order.human_attribute_name :address %>:</dt>
    <dd><%= @order.address %></dd>

    <dt><%= Order.human_attribute_name :additional_info %>:</dt>
    <dd><%= @order.additional_info %></dd>

    <dt><%= Order.human_attribute_name :price %>:</dt>
    <dd><%= number_to_currency(@order.price) %></dd>

    <dt><%= Order.human_attribute_name :status %>:</dt>
    <dd><%= I18n.t("activerecord.attributes.order.statuses.#{@order.status}")%></dd>
  </dl>
</div>

<%= render partial: 'shared/errors_exhibition', locals: {model: @order} %>
<div>
  <h2><%= Order.human_attribute_name :adjustment %></h2>
  <%= form_with model: [:owner, @order] do |order| %>
    <div>
      <%= order.label :adjustment %><br/>
      <%= order.number_field :adjustment %>
    </div>
    <br/>

    <div>
      <%= order.label :adjustment_type %><br/>
      <%= order.collection_radio_buttons :adjustment_type, Order.adjustment_type_options, :first, :last %>
    </div>
    <br/>

    <div>
      <%= order.label :adjustment_description %><br/>
      <%= order.text_area :adjustment_description %>
    </div>
    <br/>

    <div>
      <%= order.label :payment_method_id %><br/>
      <%= order.collection_radio_buttons :payment_method_id, @buffet.buffet_payment_method_options, :first, :last %>
    </div>
    <br/>

    <div>
      <%= order.label :confirmation_date %><br/>
      <%= order.date_field :confirmation_date %>
    </div>
    <br/>

    <%= order.hidden_field :status, value: :approved %>

    <%= order.submit I18n.t("helpers.models.order.approve"), data: {turbo: false}%>
  <% end %>
</div>


app/views/owner/orders/index.html.erb
<h1><%= I18n.t("helpers.models.order.my_orders") %></h1>

<div id='pending-orders'>
  <h2><%= I18n.t("helpers.models.order.pending") %></h2>
  <%= render partial: 'shared/owner_show_orders', locals: {orders_list: @pending_orders} %>
</div>

<div id='confirmed-orders'>
  <h2><%= I18n.t("helpers.models.order.confirmed") %></h2>
  <%= render partial: 'shared/owner_show_orders', locals: {orders_list: @confirmed_orders} %>
</div>

<div id='approved-orders'>
  <h2><%= I18n.t("helpers.models.order.approved") %></h2>
  <%= render partial: 'shared/owner_show_orders', locals: {orders_list: @approved_orders} %>
</div>

<div id='rejected-orders'>
  <h2><%= I18n.t("helpers.models.order.rejected") %></h2>
  <%= render partial: 'shared/owner_show_orders', locals: {orders_list: @rejected_orders} %>
</div>

app/views/owner/orders/show.html.erb
<h1><%= Order.model_name.human %></h1>

<% if @order.has_same_day_order? %>
  <p>Existe outra solicitação de evento para a mesma data</p>
<% end %>
<dl>
  <dt><%= Order.human_attribute_name :event_id %>:</dt>
  <dd><%= @order.event.name %></dd>

  <dt><%= Order.human_attribute_name :event_date %>:</dt>
  <dd><%= @order.event_date.strftime("%d/%m/%Y") %></dd>

  <dt><%= Order.human_attribute_name :total_guests %>:</dt>
  <dd><%= @order.total_guests %></dd>

  <dt><%= Order.human_attribute_name :address %>:</dt>
  <dd><%= @order.address %></dd>

  <dt><%= Order.human_attribute_name :additional_info %>:</dt>
  <dd><%= @order.additional_info %></dd>

  <dt><%= Order.human_attribute_name :price %>:</dt>
  <dd><%= number_to_currency(@order.price) %></dd>

  <dt><%= Order.human_attribute_name :code %>:</dt>
  <dd><%= @order.code %></dd>

  <dt><%= Order.human_attribute_name :status %>:</dt>
  <dd><%= I18n.t("activerecord.attributes.order.statuses.#{@order.status}")%></dd>
</dl>

<%= link_to I18n.t("helpers.models.order.message_client"), messages_path(order_id: @order.id) %>

<% if @order.status == 'pending' %>
  <div>
    <%= link_to I18n.t("helpers.models.order.analyze_request"),edit_owner_order_path(@order.id) %>
    <%= button_to I18n.t("helpers.models.order.reject_request"), owner_order_path(@order, order: { status: :rejected }), method: :patch %>
  </div>
<% end %>