config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :home, only: [:show]
  devise_for :users
  resources :messages, only: [:index, :create]
  namespace :owner do
    resources :buffets, only: [:new, :create, :show, :edit, :update] do
      resources :events, only: [:new, :create, :show, :edit, :update]
    end
    resources :event_prices, only: [:new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :dashboards, only: [:index]
  end

  namespace :client do
    resources :buffets do
      get 'search', on: :collection
    end
    resources :orders, only: [:new, :create, :show, :update]
    resources :dashboards, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show] do
        get 'search/:query', on: :collection, to: "buffets#search"
        get 'events', on: :member, to: "buffets#events"
        get ':event_id/:event_date/:total_guests', to: "buffets#check_availability"
      end
    end
  end
end

app/views/shared/_client_show_orders.html.erb
<% if orders_list.empty? %>
  <p><%= I18n.t("helpers.models.order.empty_order_list") %></p>
<% else %>
  <% orders_list.each do |order| %>
    <dl>
      <dt><%= link_to order.code, client_order_path(order.id) %></dt>
      <dd><%= order.event_date.strftime('%d/%m/%Y') %></dd>
    </dl>
  <% end %>
<% end %>

app/views/shared/_errors_exhibition.html.erb
<% if model.errors.any? %>
  <p><%= I18n.t("errors.verify") %>></p>
  <ul>
    <% model.errors.full_messages.each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_order_details.html.erb
<h2><%= I18n.t("helpers.models.order.buffet_answer") %></h2>
<dt><%= Order.human_attribute_name :adjustment %>:</dt>
<dd><%= number_to_currency(model.adjustment) %></dd>
<br/>

<dt><%= Order.human_attribute_name :adjustment_type %>:</dt>
<dd><%= I18n.t("activerecord.attributes.order.adjustment_types.#{model.adjustment_type}") %></dd>
<br/>

<dt><%= Order.human_attribute_name :adjustment_description %>:</dt>
<dd><%= model.adjustment_description %></dd>
<br/>

<dt><%= Order.human_attribute_name :payment_method_id %>:</dt>
<dd><%= model.payment_method.name %></dd>
<br/>

<dt><%= Order.human_attribute_name :confirmation_date %>:</dt>
<dd><%= model.confirmation_date.strftime("%d/%m/%Y") %></dd>

app/views/shared/_owner_show_orders.html.erb
<% if orders_list.empty? %>
  <p>Nenhuma socilitação deste tipo</p>
<% else %>
  <% orders_list.each do |order| %>
    <dl>
      <div>
        <dt><%= Order.human_attribute_name :code %></dt>
        <dd><%= link_to order.code, owner_order_path(order) %></dd>
      </div>

      <div>
        <dt><%= Order.human_attribute_name :event_id %></dt>
        <dd><%= order.event.name %></dd>
      </div>

      <div>
        <dt><%= Order.human_attribute_name :user_id %></dt>
        <dd><%= order.user.name %></dd>
      </div>
    </dl>
  <% end %>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_with url: search_client_buffets_url, method: :get, id: 'search', class: 'flex align' do |f| %>
  <%= f.label :query, I18n.t("helpers.models.message.query"), class: 'hidden-label' %>
  <div class="flex input-button-container">
    <%= f.text_field :query, placeholder: "Buscar Buffet", class: 'search-input' %>

    <%= f.button I18n.t("helpers.models.message.search"), class: "search-button" %>
  </div>
<% end %>

app/views/shared/_show_orders.html.erb
<% if orders_list.empty? %>
  <p>Nenhuma socilitação deste tipo.</p>
<% else %>
  <% orders_list.each do |order| %>
    <dl>
      <div>
        <dt><%= Order.human_attribute_name :code %></dt>
        <dd><%= link_to order.code, owner_order_path(order) %></dd>
      </div>

      <div>
        <dt><%= Order.human_attribute_name :event_id %></dt>
        <dd><%= order.event.name %></dd>
      </div>

      <div>
        <dt><%= Order.human_attribute_name :user_id %></dt>
        <dd><%= order.user.name %></dd>
      </div>
    </dl>
  <% end %>
<% end %>

app/views/shared/_unauthenticathed_user_buffet_form.html.erb
<% if @buffets.empty? %>
<p><%= I18n.t("helpers.models.buffet.any_buffets") %></p>
<% else %>
<h2><%= I18n.t("helpers.models.buffet.registered_buffets") %>:</h2>
<dl id="buffets" class="flex-vertical space-around">
    <% @buffets.each do |buffet| %>
    <div class="mini-card">
      <dt><%= link_to buffet.brand_name, home_path(buffet.id) %></dt>
      <dd><%= I18n.t("helpers.models.buffet.situated_in") %>: <%= buffet.address.city %> - <%= buffet.address.state %></dd>
    </div>
    <% end %>
</dl>
<% end %>