config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :home, only: [:show]
  devise_for :users
  resources :messages, only: [:index, :create]
  namespace :owner do
    resources :buffets, only: [:new, :create, :show, :edit, :update] do
      resources :events, only: [:new, :create, :show, :edit, :update]
    end
    resources :event_prices, only: [:new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :dashboards, only: [:index]
  end

  namespace :client do
    resources :buffets do
      get 'search', on: :collection
    end
    resources :orders, only: [:new, :create, :show, :update]
    resources :dashboards, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show] do
        get 'search/:query', on: :collection, to: "buffets#search"
        get 'events', on: :member, to: "buffets#events"
        get ':event_id/:event_date/:total_guests', to: "buffets#check_availability"
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :buffet
  has_many :event_prices
  has_many_attached :photos

  validates :name, presence: true
  validates :name, uniqueness: { scope: :buffet_id }
  validates :description, presence: true
  validates :min_guests, presence: true
  validates :max_guests, presence: true
  validates :standard_duration, presence: true
  validates :menu, presence: true
  validate :max_guest_greater_than_min_guests

  def offsite_event_status
    I18n.t(offsite_event.to_s, scope: 'boolean')
  end

  def offers_alcohol_status
    I18n.t(offers_alcohol.to_s, scope: 'boolean')
  end

  def offers_decoration_status
    I18n.t(offers_decoration.to_s, scope: 'boolean')
  end

  def offers_valet_parking_status
    I18n.t(offers_valet_parking.to_s, scope: 'boolean')
  end

  def convert_to_hours
    hours = standard_duration / 60
    minutes = standard_duration % 60

    return "#{hours}h" if minutes == 0
    "#{hours}h #{minutes}min"
  end

  def min_and_max_guests_format
    "#{min_guests} a #{max_guests}"
  end

  private

  def max_guest_greater_than_min_guests
    if min_guests >= max_guests
      errors.add(:max_guests, I18n.t("error.models.event.max_guest_greater_than_min_guests"))
    end
  end
end

app/controllers/owner/buffets_controller.rb
class Owner::BuffetsController < ApplicationController
  before_action :authenticate_owner, only: [:new, :create, :edit, :update, :show]
  before_action :set_buffet, only: [:edit, :show, :edit, :update]
  before_action :check_buffet_owner, only: [:edit, :update]

  def new
    @buffet = Buffet.new
    @buffet.build_address
  end

  def create
    @buffet = Buffet.new(buffet_params)
    @buffet.user = current_user
    if @buffet.save
      return redirect_to owner_buffet_path(@buffet), notice: t("notices.create.success", model_name: Buffet.model_name.human)
    end
    flash.now[:notice] = t("notices.create.fail", model_name: Buffet.model_name.human.downcase)
    render 'new'
  end

  def show; end

  def edit; end

  def update
    if @buffet.update(buffet_params)
      return redirect_to owner_buffet_path(@buffet), notice: t("notices.update.success", model_name: Buffet.model_name.human)
    end
    flash.now[:notice] = t("notices.update.fail", model_name: Buffet.model_name.human.downcase)
    render 'edit'
  end

  private

  def set_buffet
    @buffet = Buffet.find params[:id]
  end

  def buffet_params
    params.require(:buffet).permit(:brand_name, :company_name, :crn, :phone, :email,
                                   :description, address_attributes: [:id, :street_name,
                                    :house_or_lot_number, :neighborhood, :city, :state, :zip],
                                   payment_method_ids: [])
  end

  def check_buffet_owner
    set_buffet
    redirect_to root_path, notice: t("notices.access.access_denied") if current_user != @buffet.user
  end
end

app/controllers/owner/dashboards_controller.rb
class Owner::DashboardsController < ApplicationController
  before_action :authenticate_owner
  before_action :ensure_registered_buffet, only: [:index]
  def index
    @buffet = Buffet.find_by(user: current_user)
    @events = @buffet.events
  end
end

app/controllers/owner/event_prices_controller.rb
class Owner::EventPricesController < ApplicationController
  before_action :check_event, only: [:new, :edit, :create, :update]
  def new
    @event_price = EventPrice.new
  end

  def create
    @event_price = @event.event_prices.build(event_price_params)
    if @event.save
      redirect_to owner_buffet_event_path(@event.buffet, @event), notice: t("notices.models.event_price.register.success")
    else
      flash.now[:alert] =  t("notices.models.event_price.register.fail")
      render 'new'
    end
  end

  def edit
    @event_price = EventPrice.find params[:id]
  end

  def update
    @event_price = EventPrice.find params[:id]
    if @event_price.update(event_price_params)
      redirect_to owner_buffet_event_path(@event.buffet, @event), notice: t("notices.update.success", model_name: EventPrice.model_name.human)
    else
      flash.now[:alert] = t("notices.update.fail", model_name: EventPrice.model_name.human.downcase)
      render 'edit'
    end
  end

  private

  def event_price_params
    params.require(:event_price).permit(:standard_price, :extra_guest_price, :extra_hour_price, :day_type)
  end

  def check_event
    event = Event.find params[:event_id] || params[:event_price][:event_id]
    if event.buffet.user == current_user
      @event = event
    else
      redirect_to owner_dashboards_path, alert: t("notices.access.access_denied")
    end
  end
end

app/controllers/owner/events_controller.rb
class Owner::EventsController < ApplicationController
  def new
    @buffet = Buffet.find params[:buffet_id]
    @event = Event.new
  end

  def create
    @buffet = Buffet.find params[:buffet_id]
    @event = @buffet.events.build(event_params)
    if @event.save
      return redirect_to owner_buffet_event_path(@buffet, @event), notice: t("notices.create.success", model_name: Event.model_name.human)
    end
    flash.now[:notice] = t("notices.create.fail", model_name: Event.model_name.human.downcase)
    render 'new'
  end

  def show
    @buffet = Buffet.find params[:buffet_id]
    @event = Event.find params[:id]
  end

  def edit
    @buffet = Buffet.find params[:buffet_id]
    @event = Event.find params[:id]
  end

  def update
    @buffet = Buffet.find params[:buffet_id]
    @event = Event.find params[:id]
    if @event.update(event_params)
      return redirect_to owner_buffet_event_path(@buffet, @event), notice: t("notices.update.success", model_name: Event.model_name.human)
    end
    flash.now[:notice] = t("notices.update.success", model_name: Event.model_name.human.downcase)
    render 'edit'
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :min_guests, :max_guests, :standard_duration,
                                  :menu, :offsite_event, :offers_alcohol, :offers_decoration,
                                  :offers_valet_parking, photos: [])
  end
end

app/controllers/owner/orders_controller.rb
class Owner::OrdersController < ApplicationController
  before_action :authenticate_owner
  before_action :ensure_registered_buffet, only: [:index]

  def index
    buffet = Buffet.find_by(user: current_user)
    orders = Order.where(buffet_id: buffet.id)
    @pending_orders = orders.where(status: :pending)
    @confirmed_orders = orders.where(status: :confirmed)
    @approved_orders = orders.where(status: :approved)
    @rejected_orders = orders.where(status: :rejected)
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit
    @order = Order.find(params[:id])
    @buffet = Buffet.find_by(user: current_user)
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(params.require(:order).permit(:adjustment, :adjustment_type, :adjustment_description,
                                                   :payment_method_id, :confirmation_date, :status))
      redirect_to owner_order_path(@order), notice: t("notices.models.order.approve.success")
    else
      @buffet = Buffet.find_by(user: current_user)
      flash.now[:notice] = t("notices.models.order.approve.fail")
      render :edit
    end
  end
end

app/views/owner/events/edit.html.erb
<h1>Novo Evento</h1>

<%= render partial: 'shared/errors_exhibition', locals: {model: @event} %>

<%= form_with model: [:owner, @buffet, @event] do |event| %>
  <div>
    <%= event.label :name %>
    <%= event.text_field :name %>
  </div>
  <br/>

  <div>
    <%= event.label :description %>
    <%= event.text_field :description %>
  </div>
  <br/>

  <div>
    <%= event.label :min_guests %>
    <%= event.number_field :min_guests %>
  </div>
  <br/>

  <div>
    <%= event.label :max_guests %>
    <%= event.number_field :max_guests %>
  </div>
  <br/>

  <div>
    <%= event.label :standard_duration %> (<%= I18n.t("helpers.models.event.in_minutes") %>)
    <%= event.number_field :standard_duration %>
  </div>
  <br/>

  <div>
    <%= event.label :menu %>
    <%= event.text_area :menu %>
  </div>
  <br/>

  <div>
    <%= event.label :offsite_event %>
    <%= event.check_box :offsite_event %>
  </div>
  <br/>

  <div>
    <%= event.label :offers_alcohol %>
    <%= event.check_box :offers_alcohol %>
  </div>
  <br/>

  <div>
    <%= event.label :offers_decoration %>
    <%= event.check_box :offers_decoration %>
  </div>
  <br/>

  <div>
    <%= event.label :offers_valet_parking %>
    <%= event.check_box :offers_valet_parking %>
  </div>
  <br/>

  <%= event.submit data: {turbo: false} %>
<% end %>

app/views/owner/events/new.html.erb
<h1><%= I18n.t("helpers.models.event.create") %></h1>

<%= render partial: 'shared/errors_exhibition', locals: {model: @event} %>

<%= form_with model: [:owner, @buffet, @event] do |event| %>
  <div>
    <%= event.label :name %>
    <%= event.text_field :name %>
  </div>
  <br/>

  <div>
    <%= event.label :description %>
    <%= event.text_field :description %>
  </div>
  <br/>

  <div>
    <%= event.label :min_guests %>
    <%= event.number_field :min_guests %>
  </div>
  <br/>

  <div>
    <%= event.label :max_guests %>
    <%= event.number_field :max_guests %>
  </div>
  <br/>

  <div>
    <%= event.label :standard_duration %> (<%= I18n.t("helpers.models.event.in_minutes") %>)
    <%= event.number_field :standard_duration %>
  </div>
  <br/>

  <div>
    <%= event.label :menu %>
    <%= event.text_area :menu %>
  </div>
  <br/>

  <div>
    <%= event.label :photos %>
    <%= event.file_field :photos, multiple: true, direct_upload: true%>
  </div>
  <br/>

  <div>
    <%= event.label :offsite_event %>
    <%= event.check_box :offsite_event %>
  </div>
  <br/>

  <div>
    <%= event.label :offers_alcohol %>
    <%= event.check_box :offers_alcohol %>
  </div>
  <br/>

  <div>
    <%= event.label :offers_decoration %>
    <%= event.check_box :offers_decoration %>
  </div>
  <br/>

  <div>
    <%= event.label :offers_valet_parking %>
    <%= event.check_box :offers_valet_parking %>
  </div>
  <br/>

  <%= event.submit data: {turbo: false} %>
<% end %>

app/views/owner/events/show.html.erb
<h1><%= @event.name %></h1>

<div>
  <p><%= @event.description %></p>
  <p><%= Order.human_attribute_name :total_guests %>: de <%= @event.min_and_max_guests_format %></p>
  <p><%= Event.human_attribute_name(:standard_duration) %>: <%= @event.convert_to_hours %></p>
  <p><%= Event.human_attribute_name(:menu) %>: <%= @event.menu %></p>
  <div>
    <% @event.photos.each do |photo| %>
      <%= image_tag url_for photo %>
    <% end %>
  </div>
  <p><%= Event.human_attribute_name(:offsite_event) %>: <%= @event.offsite_event_status %></p>
  <p><%= Event.human_attribute_name(:offers_alcohol) %>: <%= @event.offers_alcohol_status %></p>
  <p><%= Event.human_attribute_name(:offers_decoration) %>: <%= @event.offers_decoration_status %></p>
  <p><%= Event.human_attribute_name(:offers_valet_parking) %>: <%= @event.offers_valet_parking_status %></p>

  <%= link_to I18n.t("helpers.models.event.edit"), edit_owner_buffet_event_path(@buffet.id, @event.id) %>
</div>

<div>
  <% @event.event_prices.each do |event_price| %>
  <h2> <%= I18n.t("activerecord.attributes.event_price.day_types.#{event_price.day_type}")%></h2>
  <p><%= EventPrice.human_attribute_name(:standard_price) %>: <%= number_to_currency(event_price.standard_price) %></p>
  <p><%= EventPrice.human_attribute_name(:extra_guest_price) %>: <%= number_to_currency(event_price.extra_guest_price) %></p>
  <p><%= EventPrice.human_attribute_name(:extra_hour_price) %>: <%= number_to_currency(event_price.extra_hour_price) %></p>

  <%= link_to I18n.t("helpers.models.event_price.edit"), edit_owner_event_price_path(event_price.id, event_id: @event.id) %>
  <% end  %>
</div>

<% if @event.event_prices.count < 2 %>
  <%= link_to I18n.t("helpers.models.event_price.create"), new_owner_event_price_path(event_id: @event.id) %>
<% end %>