config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :home, only: [:show]
  devise_for :users
  resources :messages, only: [:index, :create]
  namespace :owner do
    resources :buffets, only: [:new, :create, :show, :edit, :update] do
      resources :events, only: [:new, :create, :show, :edit, :update]
    end
    resources :event_prices, only: [:new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :dashboards, only: [:index]
  end

  namespace :client do
    resources :buffets do
      get 'search', on: :collection
    end
    resources :orders, only: [:new, :create, :show, :update]
    resources :dashboards, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show] do
        get 'search/:query', on: :collection, to: "buffets#search"
        get 'events', on: :member, to: "buffets#events"
        get ':event_id/:event_date/:total_guests', to: "buffets#check_availability"
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CadeBuffet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poetsen+One&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">
  </head>

  <body class="flex-vertical">
    <nav id="nav">
        <ul class="flex nav-background nav-content">
          <h1 class="main-title"><%= link_to "Cadê Buffet?", root_path, class: 'link-disguise'%></h1>

          <div class="flex user-area">
          <% if user_signed_in? %>
              <% if current_user.role == 'client' %>
                <%= render 'shared/search_form' %>
                <li class="flex align-center" ><%= link_to I18n.t("helpers.dashboard.client.client_area"), client_dashboards_path, class: "link-disguise" %></li>
              <% elsif current_user.role == 'owner' %>
                <li class="flex align-center"><%= link_to I18n.t("helpers.dashboard.owner.owner_area"), owner_dashboards_path, class: "link-disguise" %></li>
              <% end %>

              <div class="flex user-info align-center">
                <%= current_user_info %>
                <li><%= button_to I18n.t("helpers.dashboard.logout"), destroy_user_session_path, method: :delete %></li>
              </div>
          </div>
          <% else %>
            <div class="flex align-center search-links-container">
              <%= render 'shared/search_form' %>
              <div class="flex align-center create-session-links">
                <li class="flex align"><%= link_to I18n.t("devise.registrations.new.sign_up"), new_user_registration_path, class: 'session-link link-disguise'%></li>
                <li class="flex align"><%= link_to I18n.t("devise.sessions.new.sign_in"), new_user_session_path, class: 'session-link link-disguise' %></li>
              </div>
            </div>
          <% end %>
        </ul>
    </nav>

    <div class="flex-vertical space-around content-container">
      <%= notice %>
      <%= alert %>

      <%= yield %>
    </div>
  </body>
</html>